config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    resources :attendees , :controller => :event_attendees
    resource :locations
    collection do
      post 'bulk_update'
    end
  end

  namespace :admin do
    resources :events
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :event
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name, :description
  has_many :attendees, :dependent => :nullify
  has_many :event_groupships, :dependent => :destroy
  has_many :groups, :through => :event_groupships, :dependent => :destroy
  has_one :location, :dependent => :destroy
  belongs_to :category

  delegate :name, :to => :category, :prefix => true , :allow_nil => true
end

app/models/event_groupship.rb
class EventGroupship < ApplicationRecord
  belongs_to :event
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :event_groupships
  has_many :events , :through => :event_groupships
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :event
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

  layout "admin"
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :set_event

  def index
    @attendees = @event.attendees
  end

  def new
    @attendee = @event.attendees.new
  end

  def create
    @attendee = @event.attendees.new(attendee_params)
    if @attendee.save
      flash[:notice] = "新增成功"
      redirect_to event_attendees_path(@event)
    else
      render "new"
    end
  end

  def show
    @attendee = @event.attendees.find(params[:id])
  end

  def edit
    @attendee = @event.attendees.find(params[:id])
  end

  def update
    @attendee = @event.attendees.find(params[:id])
    if @attendee.update(attendee_params)
      flash[:notice] = "更新成功"
      redirect_to event_attendees_path(@event)
    else
      render "edit"
    end
  end

  def destroy
    @attendee = @event.attendees.find(params[:id])
    @attendee.destroy
    flash[:notice] = "刪除成功"
    redirect_to event_attendees_path(@event)
  end

  private
  def set_event
    @event = Event.find(params[:event_id])
  end

  def attendee_params
    params.require(:attendee).permit(:username)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, :only => [:show, :edit, :update, :destroy]

  def index
    if params[:keyword]
      @events = Event.where('name like ?', "%#{params[:keyword]}%")
    else
      @events = Event.all
    end

    if params[:order] == "id"
      @events = @events.order("id")
    elsif params[:order] == "name"
      @events = @events.order("name")
    end
    
    @events = @events.includes(:category).page(params[:page]).per(20)
    respond_to do |format|
      format.html { render "index" }
      format.json { render :json => @events }
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "新增成功"
      redirect_to events_path()
    else
      render "new"
    end
  end

  def show
    @title = @event.name
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:notice] = "更新成功"
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    flash[:notice] = "刪除成功"
    redirect_to events_path
  end

  def bulk_update
    ids = Array(params[:ids])
    if params[:commit] == "update"
      Event.where(:id => ids).update_all(:is_public => true)
    elsif params[:commit] == "delete"
      Event.where(:id => ids).destroy_all
    end
    redirect_to events_path
  end

  private
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :category_id, :capacity, :group_ids => [])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_event

  def new
    @location = @event.build_location
  end

  def create
    @location = @event.build_location(location_params)
    if @location.save
      redirect_to event_path(@event)
    else
      render "new"
    end
  end

  private
  def set_event
    @event = Event.find(params[:event_id])
  end

  def location_params
    params.require(:location).permit(:name)
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def show_public(is_public)
    is_public ? "開放" : "不開放"
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/admin/events/index.html.erb
admin index
て、僕、名前、朗、小学、男の人、女の人、父、母、会社員、主婦、晴子、チーズ、大好き、嫌い、

app/views/event_attendees/edit.html.erb
<h1>Edit Attendee (<%= @event.name %>)</h1>

<%= form_for @attendee, :url => event_attendee_path(@event,@attendee), :method => :patch do |f| %>
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username ,:class => "form-control"%>
    </div>
    <div class="form-group">
      <%= f.submit :class => "btn btn-danger" %>
    </div>
<% end %>

app/views/event_attendees/index.html.erb
<h1><%= @event.name %> Attendees</h1>

<ul>
  <% @attendees.each do |a| %>
      <li>
        <%= a.username %>
        <%= link_to "show" , event_attendee_path(@event,a) %>
        <%= link_to "edit" , edit_event_attendee_path(@event,a) %>
        <%= link_to "destroy" , event_attendee_path(@event,a) , :method => :delete %>
      </li>
  <% end %>
</ul>

<%= link_to "New Attendees" , new_event_attendee_path(@event),:class => "btn btn-success" %>

<%= link_to "Index" ,  events_path ,:class => "btn btn-default" %>

app/views/event_attendees/new.html.erb
<h1>New Attendee (<%= @event.name %>)</h1>

<%= form_for @attendee, :url => event_attendees_path(@event), :method => :post do |f| %>
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username ,:class => "form-control"%>
    </div>
    <div class="form-group">
      <%= f.submit :class => "btn btn-danger" %>
    </div>
<% end %>

app/views/event_attendees/show.html.erb
<h1><%= @event.name %></h1>

<h3><%= @attendee.username %></h3>

<%= link_to "back to attendees list" , event_attendees_path(@event) %>

app/views/events/_form.html.erb
<% if event.errors.any? %>
    <ul>
      <% event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :capacity %>
  <%= f.text_field :capacity, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :category_id %>
  <%= f.select :category_id, Category.all.collect { |c| [c.name, c.id] }, :prompt => "請選擇一個" %>
</div>
<div class="form-group">
  <%= f.collection_check_boxes(:group_ids, Group.all, :id, :name) %>
</div>
<div class="form-group">
  <%= f.submit :class => "btn btn-success" %>
</div>

app/views/events/edit.html.erb
<h1>Edit</h1>

<%= form_for @event, :url => event_path(@event) , :method => :patch do |f| %>
    <%= render :partial => "form", :locals => { :f => f, :event => @event } %>
<% end  %>

app/views/events/index.html.erb
<h1>Event List</h1>
<div class="btn-group">
  <%= link_to "ID", events_path(:order => "id"), :class => "btn btn-success" %>
  <%= link_to "Name", events_path(:order => "name"), :class => "btn btn-danger" %>
</div>
<%= form_tag events_path, :method => :get do %>
    <%= text_field_tag "keyword" %>
    <%= submit_tag "搜尋" %>
<% end %>
<%= form_tag bulk_update_events_path, :method => :post do %>
    <table class="table table-hover">
      <tr>
        <td>Event Name</td>
        <td>Category</td>
        <td>set_location</td>
        <td>is_public</td>
        <td>Attendees</td>
        <td>show</td>
        <td>edit</td>
        <td>destroy</td>
      </tr>
      <% @events.each do |event| %>
          <tr>
            <td><%= check_box_tag "ids[]", event.id %><%= event.name %><%= event.name %></td>
            <td><%= event.category_name %></td>
            <td><%= link_to "set_location", new_event_locations_path(event) %></td>
            <td><%= show_public(event.is_public) %></td>
            <td><%= link_to "Ateendees", event_attendees_path(event) %></td>
            <td><%= link_to "show", event_path(event) %></td>
            <td><%= link_to "edit", edit_event_path(event) %></td>
            <td><%= link_to "destroy", event_path(event, :page => params[:page]), :method => :delete %></td>
          </tr>
      <% end %>
    </table>
    <%= submit_tag "update" %>
    <%= submit_tag "delete" %>
<% end %>
<%= paginate @events %>
<%= link_to "new event", new_event_path, :class => "btn btn-success" %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_for @event, :url => events_path , :method => :post do |f| %>
    <%= render :partial => "form", :locals => { :f => f, :event => @event } %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %>(<%= @event.location.name %>)</h1>

<h3><%= @event.description %></h3>

<ul>
  <% @event.groups.each do |g| %>
      <li><%= g.name %></li>
  <% end %>
</ul>
<%= link_to "index", events_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "Webcamp12" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<h1>Admin</h1>
<p style="color: green"><%= flash[:notice] %></p>
<p style="color: red"><%= flash[:alert] %></p>
<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=  @title || "Webcamp12" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p style="color: green"><%= flash[:notice] %></p>
    <p style="color: red"><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>

app/views/locations/new.html.erb
<h1>New Location(<%= @event.name %>)</h1>

<%= form_for @location ,:url => event_locations_path(@event) , :method => :post do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name , :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit :class => "btn btn-default" %>
    </div>
<% end %>